// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efcpqtkvwonfnrzblvpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmY3BxdGt2d29uZm5yemJsdnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjEwOTYsImV4cCI6MjA3MzczNzA5Nn0.fVKESPthFFPkXvSiGZoClA8BpgZnZUU3y90uM_Vn6EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});